/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.DoctorDatabase;

/**
 *
 * @author shreyasrai
 */
public class System1 extends javax.swing.JPanel {

    /**
     * Creates new form System1
     */
    DoctorDatabase doctordatabase;
    public System1(DoctorDatabase doctordatabase) {
        initComponents();
        
        this.doctordatabase=doctordatabase;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        unamed = new javax.swing.JLabel();
        pswdd = new javax.swing.JLabel();
        userD = new javax.swing.JTextField();
        pswdD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("System Login");

        unamed.setText("User Name");

        pswdd.setText("Password");

        pswdD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdDActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unamed)
                            .addComponent(pswdd))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userD, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(pswdD)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButton1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unamed)
                    .addComponent(userD))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswdd)
                    .addComponent(pswdD))
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if( userD.getText().matches("system") && pswdD.getText().matches("system")){
            System2 system = new System2(doctordatabase);
            system.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(this, "Incorrect credential");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pswdDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pswdD;
    private javax.swing.JLabel pswdd;
    private javax.swing.JLabel unamed;
    private javax.swing.JTextField userD;
    // End of variables declaration//GEN-END:variables
}
