/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CommunityDatabase;
import model.VitalSignDatabase;
import model.Doctor;
import model.Person;
import model.PersonDatabase;
import model.Community;
import model.HospitalDatabase;
import model.Hospital;
import model.AppointmentDatabase;
import model.Appointment;
import model.DoctorDatabase;

/**
 *
 * @author shreyasrai
 */
public class System2 extends javax.swing.JFrame {

    DoctorDatabase doctordatabase;
    PersonDatabase persondatabase;
    CommunityDatabase communitydatabase;
    HospitalDatabase hospitaldatabase;
     AppointmentDatabase appointmentdatabase;
     VitalSignDatabase vitalsigndatabase;
     Doctor doctor;
     Hospital hospital;
    /**
     * Creates new form System2
     * @param doctordatabase
     * @param persondatabase
     * @param communitydatabase
     * @param hospitaldatabase
     * @param appointmentdatabase
     */
    public System2(DoctorDatabase doctordatabase, VitalSignDatabase vitalsigndatabase, PersonDatabase persondatabase, CommunityDatabase communitydatabase, HospitalDatabase hospitaldatabase, AppointmentDatabase appointmentdatabase) {
        initComponents();
        
        this.doctordatabase = doctordatabase;
        this.persondatabase = persondatabase;
        this.communitydatabase = communitydatabase;
        this.hospitaldatabase = hospitaldatabase;
        this.appointmentdatabase=appointmentdatabase;
        this.vitalsigndatabase=vitalsigndatabase;
        this.doctor=doctor;
        this.hospital=hospital;

        displayDoc();
        displayPer();
        displayCom();
        displayHos();
        fillHospitalDropDown();
        fillCommunityDropDown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_doc = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hospitaltext = new javax.swing.JTextField();
        dochospital = new javax.swing.JLabel();
        docname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        docTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        docphone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        docemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        docgender = new javax.swing.JTextField();
        doccreate = new javax.swing.JButton();
        docdelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        docage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        docspeciality = new javax.swing.JTextField();
        docexperience = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        dpswd = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        did = new javax.swing.JTextField();
        hospitaldrop = new javax.swing.JComboBox<>();
        jPanel_patient1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cTable = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        dochospital3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        ccity = new javax.swing.JTextField();
        cstate = new javax.swing.JTextField();
        cpin = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        ccountry = new javax.swing.JTextField();
        ccreate = new javax.swing.JButton();
        cdelete = new javax.swing.JButton();
        cupdate = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel_patient = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        dochospital1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hname = new javax.swing.JTextField();
        hid = new javax.swing.JTextField();
        hphone = new javax.swing.JTextField();
        hemail = new javax.swing.JTextField();
        communitytext = new javax.swing.JTextField();
        hcreate = new javax.swing.JButton();
        hdelete = new javax.swing.JButton();
        hupdate = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        hpswd = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        communitydrop = new javax.swing.JComboBox<>();
        jPanel_hospital = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        dochospital2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        pid = new javax.swing.JTextField();
        pphone = new javax.swing.JTextField();
        pemail = new javax.swing.JTextField();
        pgender = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        page = new javax.swing.JTextField();
        pbg = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        pw = new javax.swing.JTextField();
        pcreate = new javax.swing.JButton();
        pdelete = new javax.swing.JButton();
        pupdate = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        ppswd = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel_doc.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setPreferredSize(new java.awt.Dimension(1650, 1080));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Name");

        hospitaltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitaltextActionPerformed(evt);
            }
        });

        dochospital.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dochospital.setText("Hospital");

        docname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docnameActionPerformed(evt);
            }
        });

        docTable.setBackground(new java.awt.Color(0, 153, 153));
        docTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        docTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Hospital", "Phone", "Email", "Gender", "Age", "Experience", "Speciality"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        docTable.setPreferredSize(new java.awt.Dimension(1650, 1080));
        docTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(docTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Phone");

        docphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docphoneActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Email");

        docemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docemailActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Gender");

        docgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docgenderActionPerformed(evt);
            }
        });

        doccreate.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        doccreate.setText("CREATE");
        doccreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doccreateActionPerformed(evt);
            }
        });

        docdelete.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        docdelete.setText("DELETE");
        docdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docdeleteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Age");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("Speciality");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("Experience");

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel31.setText("DOCTOR");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel29.setText("Password");

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton3.setText("LogOut");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel36.setText("ID");

        did.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                didActionPerformed(evt);
            }
        });

        hospitaldrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hospitaldropItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dochospital, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(docemail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docphone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docgender)
                            .addComponent(docname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(hospitaltext, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hospitaldrop, 0, 146, Short.MAX_VALUE)))
                        .addGap(214, 214, 214)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpswd, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(docspeciality)
                                .addComponent(docexperience, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docage, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(338, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(doccreate)
                        .addGap(38, 38, 38)
                        .addComponent(docdelete)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(538, 538, 538))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {did, docage, docexperience, docspeciality, dpswd});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(docname)
                    .addComponent(jLabel5)
                    .addComponent(docage))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dochospital)
                    .addComponent(hospitaltext)
                    .addComponent(jLabel6)
                    .addComponent(docspeciality)
                    .addComponent(hospitaldrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(docphone)
                    .addComponent(docexperience)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(dpswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(docemail)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel4)
                    .addComponent(docgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doccreate)
                    .addComponent(docdelete)
                    .addComponent(jButton1))
                .addGap(189, 189, 189))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(176, 176, 176))
        );

        javax.swing.GroupLayout jPanel_docLayout = new javax.swing.GroupLayout(jPanel_doc);
        jPanel_doc.setLayout(jPanel_docLayout);
        jPanel_docLayout.setHorizontalGroup(
            jPanel_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        jPanel_docLayout.setVerticalGroup(
            jPanel_docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_docLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doctor", jPanel_doc);

        cTable.setBackground(new java.awt.Color(0, 153, 153));
        cTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient ID", "Doctor Name", "Hospital", "Doctor ID", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(cTable);

        jLabel23.setText("Patient Name");

        dochospital3.setText("Patient ID");

        jLabel24.setText("Doctor Name");

        jLabel25.setText("Hospital");

        jLabel26.setText("Doctor ID");

        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });

        ccity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccityActionPerformed(evt);
            }
        });

        cstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstateActionPerformed(evt);
            }
        });

        cpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpinActionPerformed(evt);
            }
        });

        jLabel27.setText("Date");

        ccreate.setText("CREATE");
        ccreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccreateActionPerformed(evt);
            }
        });

        cdelete.setText("DELETE");
        cdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdeleteActionPerformed(evt);
            }
        });

        cupdate.setText("UPDATE");
        cupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupdateActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Baloo Chettan 2", 1, 24)); // NOI18N
        jLabel30.setText("ENCOUNTER");

        jButton5.setText("LogOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_patient1Layout = new javax.swing.GroupLayout(jPanel_patient1);
        jPanel_patient1.setLayout(jPanel_patient1Layout);
        jPanel_patient1Layout.setHorizontalGroup(
            jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_patient1Layout.createSequentialGroup()
                .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_patient1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1338, Short.MAX_VALUE))
                    .addGroup(jPanel_patient1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_patient1Layout.createSequentialGroup()
                                .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dochospital3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cstate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ccity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpin, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(121, 121, 121)
                                .addComponent(jLabel27)
                                .addGap(58, 58, 58)
                                .addComponent(ccountry, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_patient1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(ccreate)
                                .addGap(38, 38, 38)
                                .addComponent(cdelete)
                                .addGap(38, 38, 38)
                                .addComponent(cupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addGap(78, 78, 78)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_patient1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );

        jPanel_patient1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ccity, cid, cname, cpin, cstate});

        jPanel_patient1Layout.setVerticalGroup(
            jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_patient1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_patient1Layout.createSequentialGroup()
                        .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(ccountry))
                        .addGap(213, 213, 213))
                    .addGroup(jPanel_patient1Layout.createSequentialGroup()
                        .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dochospital3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ccity)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_patient1Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_patient1Layout.createSequentialGroup()
                                .addComponent(cstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)))
                .addGroup(jPanel_patient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccreate)
                    .addComponent(cdelete)
                    .addComponent(cupdate)
                    .addComponent(jButton5))
                .addGap(158, 158, 158))
        );

        jPanel_patient1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ccity, cid, cname, cpin, cstate});

        jTabbedPane1.addTab("Encounter", jPanel_patient1);

        hTable.setBackground(new java.awt.Color(0, 153, 153));
        hTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Phone", "Email", "Community", "City", "State", "PIN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(hTable);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("Name");

        dochospital1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dochospital1.setText("ID");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("Phone");

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel11.setText("Community");

        hid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidActionPerformed(evt);
            }
        });

        hphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hphoneActionPerformed(evt);
            }
        });

        hemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hemailActionPerformed(evt);
            }
        });

        communitytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communitytextActionPerformed(evt);
            }
        });

        hcreate.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        hcreate.setText("CREATE");
        hcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcreateActionPerformed(evt);
            }
        });

        hdelete.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        hdelete.setText("DELETE");
        hdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdeleteActionPerformed(evt);
            }
        });

        hupdate.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        hupdate.setText("UPDATE");
        hupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hupdateActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel22.setText("HOSPITAL");

        jLabel33.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel33.setText("Password");

        hpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpswdActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton4.setText("LogOut");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        communitydrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                communitydropItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_patientLayout = new javax.swing.GroupLayout(jPanel_patient);
        jPanel_patient.setLayout(jPanel_patientLayout);
        jPanel_patientLayout.setHorizontalGroup(
            jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_patientLayout.createSequentialGroup()
                .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_patientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel_patientLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dochospital1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_patientLayout.createSequentialGroup()
                                .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hemail)
                                    .addComponent(hphone)
                                    .addComponent(hname, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_patientLayout.createSequentialGroup()
                                        .addComponent(communitytext, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(communitydrop, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(132, 132, 132)
                                .addComponent(jLabel33))
                            .addComponent(hid))
                        .addGap(92, 92, 92)
                        .addComponent(hpswd, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_patientLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(506, 506, 506))
            .addGroup(jPanel_patientLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(hcreate)
                .addGap(38, 38, 38)
                .addComponent(hdelete)
                .addGap(38, 38, 38)
                .addComponent(hupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(110, 110, 110))
        );

        jPanel_patientLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hemail, hid, hname, hphone});

        jPanel_patientLayout.setVerticalGroup(
            jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_patientLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_patientLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(hpswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_patientLayout.createSequentialGroup()
                        .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dochospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_patientLayout.createSequentialGroup()
                                .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hphone)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_patientLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(communitytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel_patientLayout.createSequentialGroup()
                                        .addComponent(hemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(communitydrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel_patientLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel33)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel_patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hcreate)
                            .addComponent(hdelete)
                            .addComponent(hupdate)
                            .addComponent(jButton4))))
                .addGap(85, 85, 85))
        );

        jPanel_patientLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {communitytext, hemail, hid, hname, hphone});

        jTabbedPane1.addTab("Hospital", jPanel_patient);

        pTable.setBackground(new java.awt.Color(0, 153, 153));
        pTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Phone", "Email", "Gender", "Age", "Blood Group", "Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(pTable);

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel15.setText("Name");

        dochospital2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dochospital2.setText("ID");

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel16.setText("Phone");

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel17.setText("Email");

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel18.setText("Gender");

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });

        pphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pphoneActionPerformed(evt);
            }
        });

        pemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemailActionPerformed(evt);
            }
        });

        pgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgenderActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel19.setText("Age");

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel20.setText("Blood Group");

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel21.setText("Weight");

        pcreate.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        pcreate.setText("CREATE");
        pcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcreateActionPerformed(evt);
            }
        });

        pdelete.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        pdelete.setText("DELETE");
        pdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdeleteActionPerformed(evt);
            }
        });

        pupdate.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        pupdate.setText("UPDATE");
        pupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pupdateActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel32.setText("PATIENT");

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel28.setText("Password");

        ppswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppswdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_hospitalLayout = new javax.swing.GroupLayout(jPanel_hospital);
        jPanel_hospital.setLayout(jPanel_hospitalLayout);
        jPanel_hospitalLayout.setHorizontalGroup(
            jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_hospitalLayout.createSequentialGroup()
                .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_hospitalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel_hospitalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dochospital2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pphone, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pemail, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pgender, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(230, 230, 230)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(page, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(265, 265, 265)))
                .addContainerGap())
            .addGroup(jPanel_hospitalLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(pcreate)
                .addGap(38, 38, 38)
                .addComponent(pdelete)
                .addGap(38, 38, 38)
                .addComponent(pupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_hospitalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(440, 440, 440))
        );

        jPanel_hospitalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {page, pbg, ppswd, pw});

        jPanel_hospitalLayout.setVerticalGroup(
            jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_hospitalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_hospitalLayout.createSequentialGroup()
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dochospital2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pphone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_hospitalLayout.createSequentialGroup()
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(pbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(pw))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(ppswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_hospitalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel_hospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pcreate)
                            .addComponent(pdelete)
                            .addComponent(pupdate)))
                    .addGroup(jPanel_hospitalLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton2)))
                .addGap(0, 190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patient", jPanel_hospital);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hospitaltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitaltextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitaltextActionPerformed

    private void docphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docphoneActionPerformed

    private void docemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docemailActionPerformed

    private void docgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docgenderActionPerformed

    private void doccreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doccreateActionPerformed
        // TODO add your handling code here:
        
        model.Doctor doc = doctordatabase.addNewDoctor();
        
        //doc.setDocname(docname.getText());
        doc.setDocname(docname.getText());
        doc.setHospital(hospitaldatabase.getHospital(hospitaltext.getText()));
        doc.setDocphone(docphone.getText());
        doc.setDocemail(docemail.getText());
        doc.setDocgender(docgender.getText());
        doc.setDocage(docage.getText());
        doc.setDocspeciality(docspeciality.getText());
        doc.setDocexperience(docexperience.getText());
        doc.setDid(Integer.parseInt(did.getText()));
        doc.setDpswd(dpswd.getText());
        
        JOptionPane.showMessageDialog(this, "Information Saved Successfully !!");
        
        displayDoc();
        docname.setText("");
        hospitaltext.setText("");
        docphone.setText("");
        docemail.setText("");
        docgender.setText("");
        docage.setText("");
        docspeciality.setText("");
        docexperience.setText("");
         dpswd.setText("");
        did.setText("");
        
    }//GEN-LAST:event_doccreateActionPerformed

    private void docdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docdeleteActionPerformed
        // TODO add your handling code here:
        int selected = docTable.getSelectedRow();
        
        if(selected<0){
            JOptionPane.showMessageDialog(this, "Select The Row To Delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        Doctor selectedDoc = (Doctor) model.getValueAt(selected, 0);
        
       // doctordatabase.deleteemp(selectedEmp);
        doctordatabase.deletedoc(selectedDoc);
        JOptionPane.showMessageDialog(this, "Entry Removed !!");
        
        displayDoc();
        docname.setText("");
        hospitaltext.setText("");
        docphone.setText("");
        docemail.setText("");
        docgender.setText("");
        docage.setText("");
        docspeciality.setText("");
        docexperience.setText("");
        dpswd.setText("");
        did.setText("");
    }//GEN-LAST:event_docdeleteActionPerformed

    private void docTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docTableMouseClicked
        // TODO add your handling code here:
        int selected = docTable.getSelectedRow();
        
        if(selected<0){
            JOptionPane.showMessageDialog(this, "Select The Row To View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        
        docname.setText(model.getValueAt(docTable.getSelectedRow(), 0).toString());
        hospitaltext.setText(model.getValueAt(docTable.getSelectedRow(), 1).toString());
        docphone.setText(model.getValueAt(docTable.getSelectedRow(), 2).toString());
        docemail.setText(model.getValueAt(docTable.getSelectedRow(), 3).toString());
        docgender.setText(model.getValueAt(docTable.getSelectedRow(), 4).toString());
        docage.setText(model.getValueAt(docTable.getSelectedRow(), 5).toString());
        docexperience.setText(model.getValueAt(docTable.getSelectedRow(), 6).toString());
        docspeciality.setText(model.getValueAt(docTable.getSelectedRow(), 7).toString());
        did.setText(model.getValueAt(docTable.getSelectedRow(), 8).toString());
        dpswd.setText(model.getValueAt(docTable.getSelectedRow(), 9).toString());
        
    }//GEN-LAST:event_docTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        

        int i = docTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) docTable.getModel();
        if(i >= 0)
        {           
            Doctor doc = doctordatabase.addNewDoctor();

            model.setValueAt(docname.getText(), i, 0);
            model.setValueAt(hospitaltext.getText(), i, 1);
            model.setValueAt(docphone.getText(), i, 2);
            model.setValueAt(docemail.getText(), i, 3);
            model.setValueAt(docgender.getText(), i, 4);
            model.setValueAt(docage.getText(), i, 5);
            model.setValueAt(docexperience.getText(), i, 6);
            model.setValueAt(docspeciality.getText(), i, 7);
                       model.setValueAt(did.getText(), i, 8);
            model.setValueAt(dpswd.getText(), i, 9);
           
             JOptionPane.showMessageDialog(this, "Updated Successfully !!");

        }
        else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hTableMouseClicked
        // TODO add your handling code here:
        int selected = hTable.getSelectedRow();
        
        if(selected<0){
            JOptionPane.showMessageDialog(this, "Select The Row To View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) hTable.getModel();
        
        hname.setText(model.getValueAt(hTable.getSelectedRow(), 0).toString());
        hid.setText(model.getValueAt(hTable.getSelectedRow(), 1).toString());
        hphone.setText(model.getValueAt(hTable.getSelectedRow(), 2).toString());
        hemail.setText(model.getValueAt(hTable.getSelectedRow(), 3).toString());
        communitytext.setText(model.getValueAt(hTable.getSelectedRow(), 4).toString());

        
    }//GEN-LAST:event_hTableMouseClicked

    private void hidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hidActionPerformed

    private void hphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hphoneActionPerformed

    private void hemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hemailActionPerformed

    private void communitytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communitytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communitytextActionPerformed

    private void hcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcreateActionPerformed
        // TODO add your handling code here:
        model.Hospital hos = hospitaldatabase.addNewHospital();
        
        
        hos.setHname(hname.getText());
        hos.setHid(Integer.parseInt(hid.getText()));
        hos.setHphone(Integer.parseInt(hphone.getText()));
        hos.setHemail(hemail.getText());
        hos.setCommunity(communitydatabase.getCommunity(communitytext.getText()));
        hos.setHpswd(hpswd.getText());

        
        JOptionPane.showMessageDialog(this, "Information Saved Successfully !!");
        
        displayHos();
        hname.setText("");
        hid.setText("");
        hphone.setText("");
        hemail.setText("");
        communitytext.setText("");
         hpswd.setText("");
         fillHospitalDropDown();
    }//GEN-LAST:event_hcreateActionPerformed

    private void hdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdeleteActionPerformed
        // TODO add your handling code here:
        
        int selected = hTable.getSelectedRow();
        
        if(selected<0){
            JOptionPane.showMessageDialog(this, "Select The Row To Delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) hTable.getModel();
        Hospital selectedHos = (Hospital) model.getValueAt(selected, 0);
        
        //hospitaldatabase.deletedhos(selectedHos);
        hospitaldatabase.deletedhos(selectedHos);
        JOptionPane.showMessageDialog(this, "Entry Removed !!");
        
       displayHos();
        hname.setText("");
        hid.setText("");
        hphone.setText("");
        hemail.setText("");
        communitytext.setText("");
        hpswd.setText("");

    }//GEN-LAST:event_hdeleteActionPerformed

    private void hupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hupdateActionPerformed
        // TODO add your handling code here:
        int i = hTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) hTable.getModel();
        if(i >= 0)
        {           
            Hospital hos = hospitaldatabase.addNewHospital();

            model.setValueAt(hname.getText(), i, 0);
            model.setValueAt(hid.getText(), i, 1);
            model.setValueAt(hphone.getText(), i, 2);
            model.setValueAt(hemail.getText(), i, 3);
            model.setValueAt(communitytext.getText(), i, 4);
            model.setValueAt(hpswd.getText(), i, 8);

           
           
             JOptionPane.showMessageDialog(this, "Updated Successfully !!");

        }
        else {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_hupdateActionPerformed

    private void cTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cTableMouseClicked
        // TODO add your handling code here:
         int selected = cTable.getSelectedRow();
        
        if(selected<0){
            JOptionPane.showMessageDialog(this, "Select The Row To View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) cTable.getModel();
        
        cname.setText(model.getValueAt(cTable.getSelectedRow(), 0).toString());
        cid.setText(model.getValueAt(cTable.getSelectedRow(), 1).toString());
        ccity.setText(model.getValueAt(cTable.getSelectedRow(), 2).toString());
        cstate.setText(model.getValueAt(cTable.getSelectedRow(), 3).toString());
        cpin.setText(model.getValueAt(cTable.getSelectedRow(), 4).toString());
        ccountry.setText(model.getValueAt(cTable.getSelectedRow(), 5).toString());
     
    }//GEN-LAST:event_cTableMouseClicked

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void ccityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccityActionPerformed

    private void cstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cstateActionPerformed

    private void cpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpinActionPerformed

    private void ccreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccreateActionPerformed
        // TODO add your handling code here:
        model.Community com = communitydatabase.addNewCommunity();
        
        //doc.setDocname(docname.getText());
        com.setCname(cname.getText());
        com.setCid(Integer.parseInt(cid.getText()));
        com.setCstate(cstate.getText());
        com.setCpin(Integer.parseInt(cpin.getText()));
        com.setCcountry(ccountry.getText());
        com.setCcity(ccity.getText());
       
        
        JOptionPane.showMessageDialog(this, "Information Saved Successfully !!");
        
        displayCom();
        cname.setText("");
        cid.setText("");
        cstate.setText("");
        ccity.setText("");
        cpin.setText("");
        ccountry.setText("");
    }//GEN-LAST:event_ccreateActionPerformed

    private void cdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdeleteActionPerformed
        // TODO add your handling code here:
                int selected = cTable.getSelectedRow();
        
        if(selected<0){
            JOptionPane.showMessageDialog(this, "Select The Row To Delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) cTable.getModel();
        Community selectedCom = (Community) model.getValueAt(selected, 0);
        
       // doctordatabase.deleteemp(selectedEmp);
        communitydatabase.deletedcom(selectedCom);
        JOptionPane.showMessageDialog(this, "Entry Removed !!");
        
        displayCom();
        cname.setText("");
        cid.setText("");
        cstate.setText("");
        ccity.setText("");
        cpin.setText("");
        ccountry.setText("");

    }//GEN-LAST:event_cdeleteActionPerformed

    private void cupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupdateActionPerformed
        // TODO add your handling code here:
        int i = cTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) cTable.getModel();
        if(i >= 0)
        {           
            Community com = communitydatabase.addNewCommunity();

            model.setValueAt(cname.getText(), i, 0);
            model.setValueAt(cid.getText(), i, 1);
            model.setValueAt(cstate.getText(), i, 2);
            model.setValueAt(ccity.getText(), i, 3);
            model.setValueAt(cpin.getText(), i, 4);
            model.setValueAt(ccountry.getText(), i, 5);
            
           
             JOptionPane.showMessageDialog(this, "Updated Successfully !!");

        }
        else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_cupdateActionPerformed

    private void docnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docnameActionPerformed

    private void hpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpswdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         dispose();
        //MainJFrame1 mjf = new MainJFrame1(doctordatabase, persondatabase, communitydatabase, hospitaldatabase);
        //mjf.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         dispose();
        MainJFrame1 mjf = new MainJFrame1(doctordatabase, vitalsigndatabase, persondatabase, communitydatabase, hospitaldatabase, appointmentdatabase);
        mjf.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         dispose();
        MainJFrame1 mjf = new MainJFrame1(doctordatabase, vitalsigndatabase, persondatabase, communitydatabase, hospitaldatabase, appointmentdatabase);
        mjf.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void didActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_didActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_didActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        displaytable();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void ppswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppswdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        MainJFrame1 mjf = new MainJFrame1(doctordatabase, vitalsigndatabase, persondatabase, communitydatabase, hospitaldatabase, appointmentdatabase);
        mjf.setVisible(true);

        // close current frame

    }//GEN-LAST:event_jButton2ActionPerformed

    private void pupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pupdateActionPerformed
        // TODO add your handling code here:
        int i = pTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();
        if(i >= 0)
        {
            Person per = persondatabase.addNewPerson();

            model.setValueAt(pname.getText(), i, 0);
            model.setValueAt(pid.getText(), i, 1);
            model.setValueAt(pphone.getText(), i, 2);
            model.setValueAt(pemail.getText(), i, 3);
            model.setValueAt(pgender.getText(), i, 4);
            model.setValueAt(page.getText(), i, 5);
            model.setValueAt(pbg.getText(), i, 6);
            model.setValueAt(pw.getText(), i, 7);
            model.setValueAt(ppswd.getText(), i, 8);

            JOptionPane.showMessageDialog(this, "Updated Successfully !!");

        }
        else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_pupdateActionPerformed

    private void pdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdeleteActionPerformed
        // TODO add your handling code here:
        int selected = pTable.getSelectedRow();

        if(selected<0){
            JOptionPane.showMessageDialog(this, "Select The Row To Delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();
        Person selectedPer = (Person) model.getValueAt(selected, 0);

        // doctordatabase.deleteemp(selectedEmp);
        persondatabase.deletedper(selectedPer);
        JOptionPane.showMessageDialog(this, "Entry Removed !!");

        displayPer();
        pname.setText("");
        pid.setText("");
        pphone.setText("");
        pemail.setText("");
        pgender.setText("");
        page.setText("");
        pbg.setText("");
        pw.setText("");
        ppswd.setText("");
    }//GEN-LAST:event_pdeleteActionPerformed

    private void pcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcreateActionPerformed
        // TODO add your handling code here:
        model.Person per = persondatabase.addNewPerson();

        per.setPname(pname.getText());
        per.setPid(Integer.parseInt(pid.getText()));
        per.setPphone(Integer.parseInt(pphone.getText()));
        per.setPemail(pemail.getText());
        per.setPgender(pgender.getText());
        per.setPage(Integer.parseInt(page.getText()));
        per.setPbg(pbg.getText());
        per.setPw(Integer.parseInt(pw.getText()));
        per.setPpswd(ppswd.getText());

        JOptionPane.showMessageDialog(this, "Information Saved Successfully !!");

        displayPer();
        pname.setText("");
        pid.setText("");
        pphone.setText("");
        pemail.setText("");
        pgender.setText("");
        page.setText("");
        pbg.setText("");
        pw.setText("");
        ppswd.setText("");
    }//GEN-LAST:event_pcreateActionPerformed

    private void pgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgenderActionPerformed

    private void pemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemailActionPerformed

    private void pphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pphoneActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void pTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTableMouseClicked
        // TODO add your handling code here:
        int selected = pTable.getSelectedRow();

        if(selected<0){
            JOptionPane.showMessageDialog(this, "Select The Row To View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();

        pname.setText(model.getValueAt(pTable.getSelectedRow(), 0).toString());
        pid.setText(model.getValueAt(pTable.getSelectedRow(), 1).toString());
        pphone.setText(model.getValueAt(pTable.getSelectedRow(), 2).toString());
        pemail.setText(model.getValueAt(pTable.getSelectedRow(), 3).toString());
        pgender.setText(model.getValueAt(pTable.getSelectedRow(), 4).toString());
        page.setText(model.getValueAt(pTable.getSelectedRow(), 5).toString());
        pbg.setText(model.getValueAt(pTable.getSelectedRow(), 6).toString());
        pw.setText(model.getValueAt(pTable.getSelectedRow(), 7).toString());
        ppswd.setText(model.getValueAt(pTable.getSelectedRow(), 8).toString());

    }//GEN-LAST:event_pTableMouseClicked

    private void hospitaldropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hospitaldropItemStateChanged
        // TODO add your handling code here:
        setHospitalTextArea();
        
    }//GEN-LAST:event_hospitaldropItemStateChanged

    private void communitydropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_communitydropItemStateChanged
        // TODO add your handling code here:
        setCommunityTextArea();
    }//GEN-LAST:event_communitydropItemStateChanged

    /**
     * @param args the command line arguments
     */
    
    
    private void displayDoc(){
        
       DefaultTableModel model = (DefaultTableModel) docTable.getModel();
       model.setRowCount(0);
        
       for(Doctor doc : doctordatabase.getDoctorDatabase()){
           
           Object[] row1 = new Object[10];
           row1[0] = doc;
           //row1[0] = doc.getDocname();
           row1[1] = doc.getHospital();
           row1[2] = doc.getDocphone();
           row1[3] = doc.getDocemail();
           row1[4] = doc.getDocgender();
           row1[5] = doc.getDocage();
           row1[6] = doc.getDocexperience();
           row1[7] = doc.getDocspeciality();
           row1[8] = doc.getDid();
           row1[9] = doc.getDpswd();
           
           //row1[5] = doc.get
         
           
           model.addRow(row1);
    }
    }
    
    private void displayPer(){
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();
       model.setRowCount(0);
       
       for(Person per : persondatabase.getPersonDatabase()){
           
           Object[] row2 = new Object[9];
           row2[0] = per;
           //row1[1] = per.getPname();
           row2[1] = per.getPid();
           row2[2] = per.getPphone();
           row2[3] = per.getPemail();
           row2[4] = per.getPgender();
           row2[5] = per.getPage();
           row2[6] = per.getPbg();
           row2[7] = per.getPw();
                      row2[8] = per.getPpswd();

           
           model.addRow(row2);
           
       }
    }
        private void displayCom() {
                
       DefaultTableModel model = (DefaultTableModel) cTable.getModel();
       model.setRowCount(0);
        
       for(Community com : communitydatabase.getCommunityDatabase()){
           
           Object[] row1 = new Object[6];
           row1[0] = com;
           //row1[0] = doc.getDocname();
           row1[1] = com.getCid();
           row1[2] = com.getCcity();
           row1[3] = com.getCstate();
           row1[4] = com.getCpin();
           row1[5] = com.getCcountry();
         
           
           model.addRow(row1);
    }
    }
        private void displayHos() {
            DefaultTableModel model = (DefaultTableModel) hTable.getModel();
       model.setRowCount(0);
       
       for(Hospital hos : hospitaldatabase.getHospitalDatabase()){
           
           Object[] row2 = new Object[9];
           row2[0] = hos;
           //row1[1] = per.getPname();
           row2[1] = hos.getHid();
           row2[2] = hos.getHphone();
           row2[3] = hos.getHemail();
           row2[4] = hos.getCommunity();
           row2[5] = hos.getCommunity().getCcity();
           row2[6] = hos.getCommunity().getCstate();
           row2[7] = hos.getCommunity().getCpin();
           row2[8] = hos.getHpswd();

           model.addRow(row2);
           
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cTable;
    private javax.swing.JTextField ccity;
    private javax.swing.JTextField ccountry;
    private javax.swing.JButton ccreate;
    private javax.swing.JButton cdelete;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private javax.swing.JComboBox<String> communitydrop;
    private javax.swing.JTextField communitytext;
    private javax.swing.JTextField cpin;
    private javax.swing.JTextField cstate;
    private javax.swing.JButton cupdate;
    private javax.swing.JTextField did;
    private javax.swing.JTable docTable;
    private javax.swing.JTextField docage;
    private javax.swing.JButton doccreate;
    private javax.swing.JButton docdelete;
    private javax.swing.JTextField docemail;
    private javax.swing.JTextField docexperience;
    private javax.swing.JTextField docgender;
    private javax.swing.JLabel dochospital;
    private javax.swing.JLabel dochospital1;
    private javax.swing.JLabel dochospital2;
    private javax.swing.JLabel dochospital3;
    private javax.swing.JTextField docname;
    private javax.swing.JTextField docphone;
    private javax.swing.JTextField docspeciality;
    private javax.swing.JTextField dpswd;
    private javax.swing.JTable hTable;
    private javax.swing.JButton hcreate;
    private javax.swing.JButton hdelete;
    private javax.swing.JTextField hemail;
    private javax.swing.JTextField hid;
    private javax.swing.JTextField hname;
    private javax.swing.JComboBox<String> hospitaldrop;
    private javax.swing.JTextField hospitaltext;
    private javax.swing.JTextField hphone;
    private javax.swing.JTextField hpswd;
    private javax.swing.JButton hupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_doc;
    private javax.swing.JPanel jPanel_hospital;
    private javax.swing.JPanel jPanel_patient;
    private javax.swing.JPanel jPanel_patient1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable pTable;
    private javax.swing.JTextField page;
    private javax.swing.JTextField pbg;
    private javax.swing.JButton pcreate;
    private javax.swing.JButton pdelete;
    private javax.swing.JTextField pemail;
    private javax.swing.JTextField pgender;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pphone;
    private javax.swing.JTextField ppswd;
    private javax.swing.JButton pupdate;
    private javax.swing.JTextField pw;
    // End of variables declaration//GEN-END:variables

    private void displaytable() {
        DefaultTableModel model = (DefaultTableModel) cTable.getModel();
       model.setRowCount(2);
       for(Appointment app : appointmentdatabase.getAppointmentDatabase()){
           
           Object[] row2 = new Object[5];
           row2[0] = app;
           //row1[1] = per.getPname();
//           row2[1] = app.getHos();
//           row2[2] = app.getCom();
//           row2[3] = app.getTime();
//           row2[4]=app.getName();
//           model.addRow(row2);
           row2[1] = app.getHospital().getHname();
           row2[2] = app.getCommunity().getCname();
           row2[3] = app.getTime();

           row2[4]=app.getDoctor().getDocname();
           model.addRow(row2);
           
       }
    }

    private void fillHospitalDropDown() {
                ArrayList<Hospital> hospitals = hospitaldatabase.getHospitalDatabase();
         if(hospitals!=null && hospitals.size()>0){
             DefaultComboBoxModel model = new DefaultComboBoxModel<String>();
            for(Hospital h: hospitals){
                model.addElement(h.getHname());
            }
            hospitaldrop.setModel(model);
            setHospitalTextArea();

        }
    }

    private void setCommunityTextArea() {
        communitytext.setText(communitydrop.getSelectedItem().toString());
    }

    private void fillCommunityDropDown() {
        ArrayList<Community> communities = communitydatabase.getCommunityDatabase();
        //dropcomm.setModel(new DefaultComboBoxModel<String>(communities.toArray(new String[0])));
        if(communities!=null && communities.size()>0){
        DefaultComboBoxModel model = new DefaultComboBoxModel<String>();
        for(Community c: communities){
            model.addElement(c.getCname());
        }
        communitydrop.setModel(model);
        setCommunityTextArea();
        }
    }

    private void setHospitalTextArea() {
        hospitaltext.setText(hospitaldrop.getSelectedItem().toString());
    }

    


}
