/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author shreyasrai
 */
import model.CommunityDatabase;
import model.VitalSignDatabase;
import model.HospitalDatabase;
import model.PatientDatabase;
import model.AppointmentDatabase;
import model.Community;
import model.Doctor;
import model.DoctorDatabase;
import model.Hospital;
import model.Patient;
import model.VitalSign;

/**
 *
 * @author shreyasrai
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    DoctorDatabase doctordatabase;
    PatientDatabase persondatabase;
    CommunityDatabase communitydatabase;
    HospitalDatabase hospitaldatabase;
    AppointmentDatabase appointmentdatabase;
    VitalSignDatabase vitalsigndatabase;
    public Welcome() {
        initComponents();
        doctordatabase = new DoctorDatabase();
        persondatabase = new PatientDatabase();
        communitydatabase=new CommunityDatabase();
        hospitaldatabase=new HospitalDatabase();
        appointmentdatabase=new AppointmentDatabase();
        vitalsigndatabase= new VitalSignDatabase();
        
        initDatabase();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        jButton1.setText("CLICK HERE TO START");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginPage mjf = new LoginPage(doctordatabase, vitalsigndatabase, persondatabase, communitydatabase, hospitaldatabase, appointmentdatabase);
        mjf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }
    private void initDatabase() {
        //create community
        Community c1=new Community("Roxbury",101,"Boston","MA",11099,"USA");
        Community c2=new Community("Jamaica Plain",02,"Boston","MA",02115,"USA");
        Community c3=new Community("Dorchester",03,"Boston","MA","02119","USA");
        communitydatabase.addNewCommunity(c1);
        communitydatabase.addNewCommunity(c2);

        //create hospital
        Hospital h1=new Hospital("Medical Center",85700000,"medical@gmail.com",1,"medicalcenter",c1);
        Hospital h2=new Hospital("Turffs Hospital",123,"turffs@gmail.com",2,"turffs",c2);
        hospitaldatabase.addNewHospital(h1);
        hospitaldatabase.addNewHospital(h2);
        
        //create doctor
        Doctor d1=new Doctor("Jason","85769300","jason@gmail.com","Male","32","Orthologist","12",11,"jason",h1);
        Doctor d2=new Doctor("Dr Henry","1234","doc@gmail.com","Male","45","Ortho","10 years",1,"henry",h2);
        doctordatabase.addNewDoctor(d1);
        doctordatabase.addNewDoctor(d2);
        
        //create patient
        Patient p1=new Patient("Jon",24,"Male",12345,"dd@d.com","B+",78,1,"jon",d1);
        Patient p2=new Patient("Joseph",64,"Male",12345,"dd@d.com","B+",78,2,"joseph",d2);
        persondatabase.addNewPerson(p1);
        persondatabase.addNewPerson(p2);
        
        //create vital
        VitalSign v1=new VitalSign("1","Cold","Head Ache","Mild");
        VitalSign v2=new VitalSign("2","Migraine","Head Ache","Severe");
        vitalsigndatabase.addNewVitalSign(v1);
        vitalsigndatabase.addNewVitalSign(v2);


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
